tcp:
  routers:
    mqtt:
      entrypoints: "secure-mqtt"
      service: "mqtt"
      rule: "HostSNI(`mqtt.xsystems.org`)"
      tls:
        certresolver: "xsystems"
  services:
    mqtt:
      loadbalancer:
        servers:
          - address: "mqtt:1883"
