log:
  level: "DEBUG"
api:
  dashboard: true
providers:
  file:
    directory: "/etc/traefik/services"
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
  websecure:
    address: ":443"
certificatesResolvers:
  xsystems:
    acme:
      email: "operations@xsystems.org"
      storage: "/etc/acme/xsystems.json"
      dnsChallenge:
        provider: "cloudflare"
